[package]
name = "big_text"
version = "0.2.0"
authors = ["Mikkel Schubert <MikkelSch@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.14", default-features = false, features = [
    "std",
    "suggestions",
] }
flate2 = "1.0.22"
walkdir = "2.3.2"
