[package]
name = "big_text"
version = "0.1.0"
authors = ["Mikkel Schubert <MikkelSch@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = "3.0.14"
flate2 = "1.0.22"
walkdir = "1.0.7"
